/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedNewRouteImport } from './routes/_authed/new'
import { Route as AuthedMyRequestsRouteImport } from './routes/_authed/my-requests'
import { Route as AuthedStakeWardsRouteImport } from './routes/_authed/stake/wards'
import { Route as AuthedStakeRosterRouteImport } from './routes/_authed/stake/roster'
import { Route as AuthedStakeNewRouteImport } from './routes/_authed/stake/new'
import { Route as AuthedManagerSeatsRouteImport } from './routes/_authed/manager/seats'
import { Route as AuthedManagerQueueRouteImport } from './routes/_authed/manager/queue'
import { Route as AuthedManagerImportRouteImport } from './routes/_authed/manager/import'
import { Route as AuthedManagerDashboardRouteImport } from './routes/_authed/manager/dashboard'
import { Route as AuthedManagerConfigurationRouteImport } from './routes/_authed/manager/configuration'
import { Route as AuthedManagerAuditRouteImport } from './routes/_authed/manager/audit'
import { Route as AuthedManagerAccessRouteImport } from './routes/_authed/manager/access'
import { Route as AuthedBishopricRosterRouteImport } from './routes/_authed/bishopric/roster'
import { Route as AuthedBishopricNewRouteImport } from './routes/_authed/bishopric/new'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedNewRoute = AuthedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyRequestsRoute = AuthedMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStakeWardsRoute = AuthedStakeWardsRouteImport.update({
  id: '/stake/wards',
  path: '/stake/wards',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStakeRosterRoute = AuthedStakeRosterRouteImport.update({
  id: '/stake/roster',
  path: '/stake/roster',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStakeNewRoute = AuthedStakeNewRouteImport.update({
  id: '/stake/new',
  path: '/stake/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedManagerSeatsRoute = AuthedManagerSeatsRouteImport.update({
  id: '/manager/seats',
  path: '/manager/seats',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedManagerQueueRoute = AuthedManagerQueueRouteImport.update({
  id: '/manager/queue',
  path: '/manager/queue',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedManagerImportRoute = AuthedManagerImportRouteImport.update({
  id: '/manager/import',
  path: '/manager/import',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedManagerDashboardRoute = AuthedManagerDashboardRouteImport.update({
  id: '/manager/dashboard',
  path: '/manager/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedManagerConfigurationRoute =
  AuthedManagerConfigurationRouteImport.update({
    id: '/manager/configuration',
    path: '/manager/configuration',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedManagerAuditRoute = AuthedManagerAuditRouteImport.update({
  id: '/manager/audit',
  path: '/manager/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedManagerAccessRoute = AuthedManagerAccessRouteImport.update({
  id: '/manager/access',
  path: '/manager/access',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBishopricRosterRoute = AuthedBishopricRosterRouteImport.update({
  id: '/bishopric/roster',
  path: '/bishopric/roster',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBishopricNewRoute = AuthedBishopricNewRouteImport.update({
  id: '/bishopric/new',
  path: '/bishopric/new',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-requests': typeof AuthedMyRequestsRoute
  '/new': typeof AuthedNewRoute
  '/bishopric/new': typeof AuthedBishopricNewRoute
  '/bishopric/roster': typeof AuthedBishopricRosterRoute
  '/manager/access': typeof AuthedManagerAccessRoute
  '/manager/audit': typeof AuthedManagerAuditRoute
  '/manager/configuration': typeof AuthedManagerConfigurationRoute
  '/manager/dashboard': typeof AuthedManagerDashboardRoute
  '/manager/import': typeof AuthedManagerImportRoute
  '/manager/queue': typeof AuthedManagerQueueRoute
  '/manager/seats': typeof AuthedManagerSeatsRoute
  '/stake/new': typeof AuthedStakeNewRoute
  '/stake/roster': typeof AuthedStakeRosterRoute
  '/stake/wards': typeof AuthedStakeWardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-requests': typeof AuthedMyRequestsRoute
  '/new': typeof AuthedNewRoute
  '/bishopric/new': typeof AuthedBishopricNewRoute
  '/bishopric/roster': typeof AuthedBishopricRosterRoute
  '/manager/access': typeof AuthedManagerAccessRoute
  '/manager/audit': typeof AuthedManagerAuditRoute
  '/manager/configuration': typeof AuthedManagerConfigurationRoute
  '/manager/dashboard': typeof AuthedManagerDashboardRoute
  '/manager/import': typeof AuthedManagerImportRoute
  '/manager/queue': typeof AuthedManagerQueueRoute
  '/manager/seats': typeof AuthedManagerSeatsRoute
  '/stake/new': typeof AuthedStakeNewRoute
  '/stake/roster': typeof AuthedStakeRosterRoute
  '/stake/wards': typeof AuthedStakeWardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/my-requests': typeof AuthedMyRequestsRoute
  '/_authed/new': typeof AuthedNewRoute
  '/_authed/bishopric/new': typeof AuthedBishopricNewRoute
  '/_authed/bishopric/roster': typeof AuthedBishopricRosterRoute
  '/_authed/manager/access': typeof AuthedManagerAccessRoute
  '/_authed/manager/audit': typeof AuthedManagerAuditRoute
  '/_authed/manager/configuration': typeof AuthedManagerConfigurationRoute
  '/_authed/manager/dashboard': typeof AuthedManagerDashboardRoute
  '/_authed/manager/import': typeof AuthedManagerImportRoute
  '/_authed/manager/queue': typeof AuthedManagerQueueRoute
  '/_authed/manager/seats': typeof AuthedManagerSeatsRoute
  '/_authed/stake/new': typeof AuthedStakeNewRoute
  '/_authed/stake/roster': typeof AuthedStakeRosterRoute
  '/_authed/stake/wards': typeof AuthedStakeWardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-requests'
    | '/new'
    | '/bishopric/new'
    | '/bishopric/roster'
    | '/manager/access'
    | '/manager/audit'
    | '/manager/configuration'
    | '/manager/dashboard'
    | '/manager/import'
    | '/manager/queue'
    | '/manager/seats'
    | '/stake/new'
    | '/stake/roster'
    | '/stake/wards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-requests'
    | '/new'
    | '/bishopric/new'
    | '/bishopric/roster'
    | '/manager/access'
    | '/manager/audit'
    | '/manager/configuration'
    | '/manager/dashboard'
    | '/manager/import'
    | '/manager/queue'
    | '/manager/seats'
    | '/stake/new'
    | '/stake/roster'
    | '/stake/wards'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/my-requests'
    | '/_authed/new'
    | '/_authed/bishopric/new'
    | '/_authed/bishopric/roster'
    | '/_authed/manager/access'
    | '/_authed/manager/audit'
    | '/_authed/manager/configuration'
    | '/_authed/manager/dashboard'
    | '/_authed/manager/import'
    | '/_authed/manager/queue'
    | '/_authed/manager/seats'
    | '/_authed/stake/new'
    | '/_authed/stake/roster'
    | '/_authed/stake/wards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/new': {
      id: '/_authed/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthedNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my-requests': {
      id: '/_authed/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof AuthedMyRequestsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stake/wards': {
      id: '/_authed/stake/wards'
      path: '/stake/wards'
      fullPath: '/stake/wards'
      preLoaderRoute: typeof AuthedStakeWardsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stake/roster': {
      id: '/_authed/stake/roster'
      path: '/stake/roster'
      fullPath: '/stake/roster'
      preLoaderRoute: typeof AuthedStakeRosterRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stake/new': {
      id: '/_authed/stake/new'
      path: '/stake/new'
      fullPath: '/stake/new'
      preLoaderRoute: typeof AuthedStakeNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/manager/seats': {
      id: '/_authed/manager/seats'
      path: '/manager/seats'
      fullPath: '/manager/seats'
      preLoaderRoute: typeof AuthedManagerSeatsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/manager/queue': {
      id: '/_authed/manager/queue'
      path: '/manager/queue'
      fullPath: '/manager/queue'
      preLoaderRoute: typeof AuthedManagerQueueRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/manager/import': {
      id: '/_authed/manager/import'
      path: '/manager/import'
      fullPath: '/manager/import'
      preLoaderRoute: typeof AuthedManagerImportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/manager/dashboard': {
      id: '/_authed/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof AuthedManagerDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/manager/configuration': {
      id: '/_authed/manager/configuration'
      path: '/manager/configuration'
      fullPath: '/manager/configuration'
      preLoaderRoute: typeof AuthedManagerConfigurationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/manager/audit': {
      id: '/_authed/manager/audit'
      path: '/manager/audit'
      fullPath: '/manager/audit'
      preLoaderRoute: typeof AuthedManagerAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/manager/access': {
      id: '/_authed/manager/access'
      path: '/manager/access'
      fullPath: '/manager/access'
      preLoaderRoute: typeof AuthedManagerAccessRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bishopric/roster': {
      id: '/_authed/bishopric/roster'
      path: '/bishopric/roster'
      fullPath: '/bishopric/roster'
      preLoaderRoute: typeof AuthedBishopricRosterRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bishopric/new': {
      id: '/_authed/bishopric/new'
      path: '/bishopric/new'
      fullPath: '/bishopric/new'
      preLoaderRoute: typeof AuthedBishopricNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedMyRequestsRoute: typeof AuthedMyRequestsRoute
  AuthedNewRoute: typeof AuthedNewRoute
  AuthedBishopricNewRoute: typeof AuthedBishopricNewRoute
  AuthedBishopricRosterRoute: typeof AuthedBishopricRosterRoute
  AuthedManagerAccessRoute: typeof AuthedManagerAccessRoute
  AuthedManagerAuditRoute: typeof AuthedManagerAuditRoute
  AuthedManagerConfigurationRoute: typeof AuthedManagerConfigurationRoute
  AuthedManagerDashboardRoute: typeof AuthedManagerDashboardRoute
  AuthedManagerImportRoute: typeof AuthedManagerImportRoute
  AuthedManagerQueueRoute: typeof AuthedManagerQueueRoute
  AuthedManagerSeatsRoute: typeof AuthedManagerSeatsRoute
  AuthedStakeNewRoute: typeof AuthedStakeNewRoute
  AuthedStakeRosterRoute: typeof AuthedStakeRosterRoute
  AuthedStakeWardsRoute: typeof AuthedStakeWardsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedMyRequestsRoute: AuthedMyRequestsRoute,
  AuthedNewRoute: AuthedNewRoute,
  AuthedBishopricNewRoute: AuthedBishopricNewRoute,
  AuthedBishopricRosterRoute: AuthedBishopricRosterRoute,
  AuthedManagerAccessRoute: AuthedManagerAccessRoute,
  AuthedManagerAuditRoute: AuthedManagerAuditRoute,
  AuthedManagerConfigurationRoute: AuthedManagerConfigurationRoute,
  AuthedManagerDashboardRoute: AuthedManagerDashboardRoute,
  AuthedManagerImportRoute: AuthedManagerImportRoute,
  AuthedManagerQueueRoute: AuthedManagerQueueRoute,
  AuthedManagerSeatsRoute: AuthedManagerSeatsRoute,
  AuthedStakeNewRoute: AuthedStakeNewRoute,
  AuthedStakeRosterRoute: AuthedStakeRosterRoute,
  AuthedStakeWardsRoute: AuthedStakeWardsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
