// Hardcoded canonical calling names used for typeahead on the New
// Request form's `reason` field. Stake-scoped requests filter against
// `STAKE_CALLINGS`; ward-scoped against `WARD_CALLINGS`. Free-text
// values outside these lists are still accepted on submit; the lists
// are suggestion hints only.
//
// List order is intentional (organisational hierarchy) — preserve it.
// Edit by source control; this file is the source of truth.

/** Standard ward-level callings. Surfaced when the request scope is a ward. */
export const WARD_CALLINGS: readonly string[] = [
  'Bishop',
  'Bishopric First Counselor',
  'Bishopric Second Counselor',
  'Ward Executive Secretary',
  'Ward Assistant Executive Secretary',
  'Ward Clerk',
  'Ward Assistant Clerk',
  'Ward Assistant Clerk--Membership',
  'Ward Assistant Clerk--Finance',
  'Elders Quorum President',
  'Elders Quorum First Counselor',
  'Elders Quorum Second Counselor',
  'Elders Quorum Secretary',
  'Elders Quorum Assistant Secretary',
  'Relief Society President',
  'Relief Society First Counselor',
  'Relief Society Second Counselor',
  'Relief Society Secretary',
  'Aaronic Priesthood Advisors',
  'Aaronic Priesthood Specialists',
  'Young Women President',
  'Young Women First Counselor',
  'Young Women Second Counselor',
  'Young Women Secretary',
  'Young Women Advisors',
  'Young Women Specialists',
  'Sunday School President',
  'Sunday School First Counselor',
  'Sunday School Second Counselor',
  'Sunday School Secretary',
  'Primary President',
  'Primary First Counselor',
  'Primary Second Counselor',
  'Primary Secretary',
  'Ward Mission Leader',
  'Assistant Ward Mission Leader',
  'Temple and Family History Leader',
  'Young Single Adult Adviser',
  'History Specialist',
  'Email Communication Specialist',
  'Building Representative',
];

/** Standard stake-level callings. Surfaced when the request scope is `'stake'`. */
export const STAKE_CALLINGS: readonly string[] = [
  'Stake President',
  'Stake Presidency First Counselor',
  'Stake Presidency Second Counselor',
  'Stake Clerk',
  'Stake Assistant Clerk',
  'Stake Assistant Clerk--Membership',
  'Stake Assistant Clerk--Finance',
  'Stake Executive Secretary',
  'Stake Assistant Executive Secretary',
  'Stake High Councilor',
  'Stake Patriarch',
  'Stake Relief Society President',
  'Stake Relief Society First Counselor',
  'Stake Relief Society Second Counselor',
  'Stake Relief Society Secretary',
  'Stake Young Men President',
  'Stake Young Men First Counselor',
  'Stake Young Men Second Counselor',
  'Stake Young Men Secretary',
  'Stake Young Women President',
  'Stake Young Women First Counselor',
  'Stake Young Women Second Counselor',
  'Stake Young Women Secretary',
  'Stake Sunday School President',
  'Stake Sunday School First Counselor',
  'Stake Sunday School Second Counselor',
  'Stake Sunday School Secretary',
  'Stake Primary President',
  'Stake Primary First Counselor',
  'Stake Primary Second Counselor',
  'Stake Primary Secretary',
  'Stake History Specialist',
  'Stake Single Adult Adviser',
  'Stake Single Adult Representative',
  'Stake Young Single Adult Representative',
  'Stake Music Chairman',
  'Stake Audit Committee',
  'Stake Auditor',
];
