// Pre-build step run by the Firebase deploy scripts (deploy-staging.sh,
// deploy-prod.sh) before `pnpm build`. Writes the same UTC ISO timestamp
// + git short SHA into two files:
//
//   apps/web/src/version.ts        — consumed by the SPA shell topbar
//                                    (KINDOO_WEB_VERSION) and reserved
//                                    for a future footer (KINDOO_WEB_BUILT_AT)
//   functions/src/version.ts       — bundled into the Cloud Functions
//                                    deploy artifact so an operator can
//                                    confirm the deployed bundle matches
//                                    the most recent deploy
//                                    (KINDOO_FUNCTIONS_VERSION; reserved
//                                    KINDOO_FUNCTIONS_BUILT_AT)
//
// Per-workspace named exports (KINDOO_WEB_*, KINDOO_FUNCTIONS_*) make
// the constants self-documenting at every call site — `KINDOO_WEB_VERSION`
// in the SPA topbar reads correctly out of context, where a bare
// `VERSION` would not. The naming also prevents accidental cross-import
// (the functions code can't import the web version constant by name).
//
// Cross-platform: pure Node, no shell-quoting gymnastics. Imported by
// deploy-staging.sh / deploy-prod.sh as `node infra/scripts/stamp-version.js`.
//
// The committed source contents of both version.ts files are dev
// placeholders ('0.0.0-dev') so `pnpm dev` and `pnpm test` work without
// running this script. Each deploy run overwrites them with the real
// stamp before `pnpm build`. The deploy scripts treat the post-stamp
// files as build artifacts; the operator does not commit them.

const fs = require('fs');
const path = require('path');
const child_process = require('child_process');

const repoRoot = path.resolve(__dirname, '..', '..');
const builtAt = new Date().toISOString();

let gitSha = 'unknown';
try {
  gitSha = child_process
    .execSync('git rev-parse --short HEAD', { cwd: repoRoot })
    .toString()
    .trim();
} catch {
  // Not a git checkout, or git not installed; fall through with 'unknown'.
}

// Each target declares the prefix used for its named exports. Keeping
// the prefix per-target (rather than deriving from path) makes the map
// from "this workspace" → "this constant name" explicit and greppable.
const targets = [
  {
    file: path.join(repoRoot, 'apps', 'web', 'src', 'version.ts'),
    prefix: 'KINDOO_WEB',
  },
  {
    file: path.join(repoRoot, 'functions', 'src', 'version.ts'),
    prefix: 'KINDOO_FUNCTIONS',
  },
];

const banner =
  '// Auto-generated by infra/scripts/stamp-version.js — do not edit by hand.\n' +
  '// Regenerated by every deploy script run (deploy-staging.sh, deploy-prod.sh).\n' +
  '// The values let an operator verify the served bundle matches the most recent\n' +
  '// deploy: compare the value rendered in the SPA topbar (apps/web) or bundled\n' +
  '// into the Cloud Functions deploy artifact (functions) to the value committed here.\n';

// Emit single-quoted string literals so the stamped file matches the
// repo prettier config (singleQuote: true). Both `gitSha` (a 7-char
// hex string) and `builtAt` (a UTC ISO timestamp) are guaranteed not
// to contain a single quote, so a naive concatenation is safe.
function bodyFor(prefix) {
  return (
    banner +
    'export const ' +
    prefix +
    "_VERSION = '" +
    gitSha +
    "';\n" +
    'export const ' +
    prefix +
    "_BUILT_AT = '" +
    builtAt +
    "';\n"
  );
}

let wrote = 0;
let skipped = 0;

for (const target of targets) {
  const dir = path.dirname(target.file);
  if (!fs.existsSync(dir)) {
    // Directory doesn't exist yet (e.g., apps/web/src/ before web-engineer
    // creates it in Phase 1). Skip silently — the deploy script will fail
    // later with a clearer error if the build itself can't find a source dir.
    skipped++;
    continue;
  }
  fs.writeFileSync(target.file, bodyFor(target.prefix), 'utf8');
  wrote++;
}

console.log(
  'stamp-version: wrote ' +
    wrote +
    ' file(s), skipped ' +
    skipped +
    ' missing dir(s) — sha=' +
    gitSha +
    ' builtAt=' +
    builtAt,
);
