// Pre-build step run by the Firebase deploy scripts (deploy-staging.sh,
// deploy-prod.sh) before `pnpm build`. Writes the same UTC ISO timestamp
// + git short SHA into two files:
//
//   apps/web/src/version.ts        — consumed by the SPA footer
//   functions/src/version.ts       — consumed by the `hello` callable
//                                    (returns {version, builtAt, env})
//
// The two files don't exist yet — web-engineer creates apps/web/src/
// in Phase 1 sub-tasks; backend-engineer creates functions/src/ in
// Phase 1 sub-tasks. This script is forward-looking: when those
// directories appear, the deploy scripts will pre-write version.ts
// before each build.
//
// Format mirrors the Apps Script side's scripts/stamp-version.js:
// a UTC ISO timestamp the SPA renders in a small footer so an operator
// can confirm "the cache served what we deployed last."
//
// Cross-platform: pure Node, no shell-quoting gymnastics. Imported by
// deploy-staging.sh / deploy-prod.sh as `node infra/scripts/stamp-version.js`.

const fs = require('fs');
const path = require('path');
const child_process = require('child_process');

const repoRoot = path.resolve(__dirname, '..', '..');
const builtAt = new Date().toISOString();

let gitSha = 'unknown';
try {
  gitSha = child_process
    .execSync('git rev-parse --short HEAD', { cwd: repoRoot })
    .toString()
    .trim();
} catch {
  // Not a git checkout, or git not installed; fall through with 'unknown'.
}

const targets = [
  path.join(repoRoot, 'apps', 'web', 'src', 'version.ts'),
  path.join(repoRoot, 'functions', 'src', 'version.ts'),
];

const banner =
  '// Auto-generated by infra/scripts/stamp-version.js — do not edit by hand.\n' +
  '// Regenerated by every deploy script run (deploy-staging.sh, deploy-prod.sh).\n' +
  '// The values let an operator verify the served bundle matches the most recent\n' +
  '// deploy: compare the value rendered in the SPA footer (apps/web) or returned\n' +
  '// by the `hello` callable (functions) to the value committed here.\n';

const body =
  banner +
  'export const VERSION = ' +
  JSON.stringify(gitSha) +
  ';\n' +
  'export const BUILT_AT = ' +
  JSON.stringify(builtAt) +
  ';\n';

let wrote = 0;
let skipped = 0;

for (const target of targets) {
  const dir = path.dirname(target);
  if (!fs.existsSync(dir)) {
    // Directory doesn't exist yet (e.g., apps/web/src/ before web-engineer
    // creates it in Phase 1). Skip silently — the deploy script will fail
    // later with a clearer error if the build itself can't find a source dir.
    skipped++;
    continue;
  }
  fs.writeFileSync(target, body, 'utf8');
  wrote++;
}

console.log(
  'stamp-version: wrote ' +
    wrote +
    ' file(s), skipped ' +
    skipped +
    ' missing dir(s) — sha=' +
    gitSha +
    ' builtAt=' +
    builtAt,
);
