// Pre-build step run by the Firebase deploy scripts (deploy-staging.sh,
// deploy-prod.sh) before `pnpm build`. Writes the same UTC ISO timestamp
// + git short SHA into two gitignored generated files:
//
//   apps/web/src/version.gen.ts        — re-exported from
//                                        apps/web/src/version.ts as
//                                        KINDOO_WEB_VERSION /
//                                        KINDOO_WEB_BUILT_AT
//   functions/src/version.gen.ts       — re-exported from
//                                        functions/src/version.ts as
//                                        KINDOO_FUNCTIONS_VERSION /
//                                        KINDOO_FUNCTIONS_BUILT_AT
//
// Both `version.ts` files are committed and stable; the `version.gen.ts`
// payloads are gitignored. That separation is what keeps the deploy
// guard's clean-tree check satisfied after the stamper runs.
//
// Per-workspace named exports (KINDOO_WEB_*, KINDOO_FUNCTIONS_*) make
// the constants self-documenting at every call site — `KINDOO_WEB_VERSION`
// in the SPA topbar reads correctly out of context, where a bare
// `VERSION` would not. The naming also prevents accidental cross-import
// (the functions code can't import the web version constant by name).
//
// Cross-platform: pure Node, no shell-quoting gymnastics. Imported by
// deploy-staging.sh / deploy-prod.sh as `node infra/scripts/stamp-version.js`.
//
// Outside of deploy, `infra/scripts/ensure-version-gen.js` (run by the
// root `prepare` script after `pnpm install`) seeds each gen file with
// dev placeholders ('0.0.0-dev' / 'dev'), so `pnpm dev` and `pnpm test`
// work without ever running this stamper.

const fs = require('fs');
const path = require('path');
const child_process = require('child_process');

const repoRoot = path.resolve(__dirname, '..', '..');
const builtAt = new Date().toISOString();

let gitSha = 'unknown';
try {
  gitSha = child_process
    .execSync('git rev-parse --short HEAD', { cwd: repoRoot })
    .toString()
    .trim();
} catch {
  // Not a git checkout, or git not installed; fall through with 'unknown'.
}

// Each target declares the prefix used for its named exports. Keeping
// the prefix per-target (rather than deriving from path) makes the map
// from "this workspace" → "this constant name" explicit and greppable.
const targets = [
  {
    file: path.join(repoRoot, 'apps', 'web', 'src', 'version.gen.ts'),
    prefix: 'KINDOO_WEB',
  },
  {
    file: path.join(repoRoot, 'functions', 'src', 'version.gen.ts'),
    prefix: 'KINDOO_FUNCTIONS',
  },
];

const banner =
  '// Auto-generated by infra/scripts/stamp-version.js (deploy stamp).\n' +
  '// Gitignored — do not commit. Overwritten on every deploy.\n';

// Emit single-quoted string literals so the stamped file matches the
// repo prettier config (singleQuote: true). Both `gitSha` (a 7-char
// hex string) and `builtAt` (a UTC ISO timestamp) are guaranteed not
// to contain a single quote, so a naive concatenation is safe.
function bodyFor(prefix) {
  return (
    banner +
    'export const ' +
    prefix +
    "_VERSION = '" +
    gitSha +
    "';\n" +
    'export const ' +
    prefix +
    "_BUILT_AT = '" +
    builtAt +
    "';\n"
  );
}

let wrote = 0;
let skipped = 0;

for (const target of targets) {
  const dir = path.dirname(target.file);
  if (!fs.existsSync(dir)) {
    // Directory doesn't exist yet (e.g., apps/web/src/ before web-engineer
    // creates it in Phase 1). Skip silently — the deploy script will fail
    // later with a clearer error if the build itself can't find a source dir.
    skipped++;
    continue;
  }
  fs.writeFileSync(target.file, bodyFor(target.prefix), 'utf8');
  wrote++;
}

console.log(
  'stamp-version: wrote ' +
    wrote +
    ' file(s), skipped ' +
    skipped +
    ' missing dir(s) — sha=' +
    gitSha +
    ' builtAt=' +
    builtAt,
);
