// Pre-push step run by `npm run push` and `npm run push:watch`.
//
// Writes a UTC ISO timestamp into src/core/Version.gs. The Layout shell
// renders the value in a small footer on every page; comparing the value
// shown in the browser against the value committed to this file lets you
// detect a stale Apps Script deployment (Apps Script's /exec URL serves
// the last *deployed* version, which can drift behind the head if you
// forget to do "Manage deployments → Edit → New version" after a push).
//
// Cross-platform: pure Node, no shell-quoting gymnastics.

const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'src', 'core', 'Version.gs');
const ts = new Date().toISOString();
const content =
  '// Auto-generated by `npm run push` via scripts/stamp-version.js.\n' +
  '// Do not edit by hand — your changes will be overwritten on the next push.\n' +
  '//\n' +
  '// The value is a UTC ISO timestamp of the most recent push and serves as\n' +
  '// a "deployment freshness" indicator. The Layout shell renders it in a\n' +
  '// small footer on every page; if the value in the browser doesn\'t match\n' +
  '// what\'s in this file, your /exec deployment is serving stale code (use\n' +
  '// Apps Script editor → Deploy → Manage deployments → Edit → New version\n' +
  '// → Deploy to update it).\n' +
  'const KINDOO_VERSION_ = ' + JSON.stringify(ts) + ';\n' +
  'function Version_get() { return KINDOO_VERSION_; }\n';

fs.writeFileSync(filePath, content, 'utf8');
console.log('stamp-version: ' + ts);
